import json
import re
import shutil
from pathlib import Path
from typing import Any

from backend.agentgate.core.product_config import ReleaseCheckConfig
from backend.agentgate.demo.trace_seed_generator import write_seed_evidence
from backend.agentgate.main import app
from backend.agentgate.release import release_check as release_check_module
from backend.agentgate.release.release_check import run_release_check
from backend.agentgate.web import routes_dashboard
from backend.agentgate.web.report_renderer import (
    build_report_context,
    future_verification_run_card_copy,
)
from fastapi.testclient import TestClient


def _seed(version: str, tmp_path: Path) -> Path:
    output = tmp_path / f"seed_{version.replace('.', '')}_evidence.jsonl"
    write_seed_evidence(version, output)
    return output


def _write_artifacts(version: str, target: Path, tmp_path: Path) -> None:
    run_release_check(_seed(version, tmp_path), target)


def _rewrite_json(path: Path, update: Any) -> None:
    payload = json.loads(path.read_text(encoding="utf-8"))
    update(payload)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _mark_warning_only_failure(output_dir: Path) -> None:
    metrics_path = output_dir / "metrics_summary.json"

    def update(payload: dict[str, Any]) -> None:
        for metric in payload["metrics"]:
            if metric.get("decision_impact") != "warning":
                continue
            if metric["name"] == "intent_routing_accuracy":
                metric["value"] = 0.91
                metric["passes_threshold"] = False
            else:
                metric["passes_threshold"] = True

    _rewrite_json(metrics_path, update)


def test_landing_shows_v2_blockers_when_latest_is_approved(
    tmp_path: Path, monkeypatch: Any
) -> None:
    latest_dir = tmp_path / "latest"
    v2_dir = tmp_path / "v2"
    v21_dir = tmp_path / "v21"
    _write_artifacts("v2.1", latest_dir, tmp_path)
    _write_artifacts("v2", v2_dir, tmp_path)
    _write_artifacts("v2.1", v21_dir, tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/")

    assert response.status_code == 200
    assert "APPROVED" in response.text
    assert "Reference workflow:" in response.text
    assert "Reference Ops AI" in response.text
    assert "blocked-card-grid" in response.text
    assert "View blocker evidence detail" in response.text
    assert "Release controls generated" in response.text
    assert "Policy expected DENY" in response.text


def test_landing_features_reference_intervention_and_demotes_latest_run(
    tmp_path: Path, monkeypatch: Any
) -> None:
    latest_dir = tmp_path / "latest"
    v2_dir = tmp_path / "v2"
    v21_dir = tmp_path / "v21"
    _write_artifacts("v2.1", latest_dir, tmp_path)
    _write_artifacts("v2", v2_dir, tmp_path)
    _write_artifacts("v2.1", v21_dir, tmp_path)
    _mark_warning_only_failure(v21_dir)
    _rewrite_json(
        latest_dir / "release_decision.json",
        lambda payload: payload.__setitem__("agent_version", "v9.9"),
    )
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/")

    assert response.status_code == 200
    assert "AgentGate stopped a dangerous AI agent release" in response.text
    assert "Featured release intervention" in response.text
    assert "v2" in response.text
    assert "BLOCKED" in response.text
    assert "deep_investigate_alert" in response.text
    assert response.text.index("Policy expected DENY") < response.text.index(
        "A low-privilege role reached `deep_investigate_alert` in controlled release evidence."
    )
    assert "Generated release controls" in response.text
    assert "Policy expected DENY" in response.text
    assert "AgentGate blocked v2 before release and generated controls" in response.text
    assert "Operational status" not in response.text
    assert "Latest run can change" not in response.text
    assert "v9.9" not in response.text
    assert "v2.1 verified the controls generated by the blocked v2 release." in response.text
    assert "Approved, not perfect — non-blocking warnings remain visible." in response.text


def test_landing_hero_and_how_it_works_copy(tmp_path: Path, monkeypatch: Any) -> None:
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(tmp_path / "missing"))
    client = TestClient(app)

    response = client.get("/")

    assert response.status_code == 200
    assert "Block unsafe AI agent releases before production." in response.text
    assert "Phoenix evidence path" in response.text
    assert "Candidate evidence" in response.text
    assert "two AI agents" not in response.text
    assert "Every Failed Trace" not in response.text
    assert "Production agent" not in response.text


def test_landing_renders_without_latest_artifacts(tmp_path: Path, monkeypatch: Any) -> None:
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(tmp_path / "missing"))
    client = TestClient(app)

    response = client.get("/")

    assert response.status_code == 200
    assert "Release authority" in response.text
    assert "Block unsafe AI agent releases before production" in response.text
    assert "No report" in response.text
    assert "Candidate under review" in response.text
    assert "Where each piece sits" in response.text
    assert "Open latest report" in response.text
    assert "gate-bound metrics" in response.text
    assert "How it works" in response.text
    assert "gate-bound metrics" in response.text
    assert "Phoenix MCP" in response.text
    assert "Human stays in control" not in response.text
    assert "What AgentGate does not do" not in response.text
    assert "crash log" not in response.text.lower()


def test_run_page_renders_stepper_and_phoenix_defaults(tmp_path: Path, monkeypatch: Any) -> None:
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(tmp_path / "missing"))
    monkeypatch.setenv("PHOENIX_PROJECT_NAME", "agentgate-reference-ops-demo")
    client = TestClient(app)

    response = client.get("/run")

    assert response.status_code == 200
    assert "Workflow progress" in response.text
    assert "Load candidate evidence" not in response.text
    assert "Collect candidate evidence" in response.text
    assert "Apply AgentPack policy" in response.text
    assert "Evaluate blocker and warning controls" in response.text
    assert "Verify inherited release controls" in response.text
    assert "Generate future controls if blocked" in response.text
    assert "Write ship / no-ship decision" in response.text
    assert "Render audit report" in response.text
    assert "gemini-flash-latest" in response.text
    assert "Diagnosis model" in response.text
    assert 'data-step="0"' in response.text
    assert "step-status" in response.text
    assert 'const REPORT_URL = "/reports/latest"' in response.text
    assert "window.location.assign(REPORT_URL)" in response.text
    assert 'id="event-console"' not in response.text
    assert 'id="run-summary"' in response.text
    assert 'id="candidate-version"' in response.text
    assert "Candidate agent version" in response.text
    assert "Run release check" in response.text
    assert "Before you run" in response.text
    assert "v2.1 verifies the release controls generated by the blocked v2 run." in response.text
    assert (
        "When no explicit reference is provided, AgentGate uses the bundled v2 controls."
        in response.text
    )
    assert "Primary workflow language" not in response.text
    assert "Each run produces a reproducible release decision and audit report." in response.text
    assert "Choose a candidate version. AgentGate loads candidate evidence" in response.text
    assert "reference workflow" not in response.text.lower()
    assert "Phoenix project" in response.text
    assert "Ready to run" in response.text
    assert "/reports/latest" in response.text
    assert "Latest saved decision:" not in response.text
    assert "Run check" in response.text
    assert "agentgate-reference-ops-demo" in response.text
    assert (
        response.text.index("Collect candidate evidence")
        < response.text.index("Apply AgentPack policy")
        < response.text.index("Evaluate blocker and warning controls")
        < response.text.index("Verify inherited release controls")
        < response.text.index("Generate future controls if blocked")
        < response.text.index("Write ship / no-ship decision")
        < response.text.index("Render audit report")
    )


def test_run_page_uses_no_ship_language_for_latest_blocked_candidate(
    tmp_path: Path, monkeypatch: Any
) -> None:
    latest_dir = tmp_path / "latest"
    _write_artifacts("v2", latest_dir, tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/run")

    assert response.status_code == 200
    assert "Last completed run:" in response.text
    assert "<strong>v2</strong>" in response.text
    assert "No-ship (BLOCKED)" in response.text
    assert 'value="v2" selected' in response.text
    assert "Latest saved decision:" not in response.text


def test_run_page_uses_ship_with_warnings_language_for_latest_v21(
    tmp_path: Path, monkeypatch: Any
) -> None:
    latest_dir = tmp_path / "latest"
    _write_artifacts("v2.1", latest_dir, tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/run")

    assert response.status_code == 200
    assert "Last completed run:" in response.text
    assert "<strong>v2.1</strong>" in response.text
    assert "Ship (APPROVED)" in response.text
    assert 'value="v2.1" selected' in response.text
    assert "Latest saved decision:" not in response.text


def test_latest_report_renders_single_candidate_artifacts(tmp_path: Path, monkeypatch: Any) -> None:
    latest_dir = tmp_path / "latest"
    _write_artifacts("v2", latest_dir, tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/reports/latest")

    assert response.status_code == 200
    assert "Candidate report" in response.text
    assert "BLOCKED" in response.text
    assert "Why blocked" in response.text
    assert "Release controls generated from this blocked failure" in response.text
    assert "Fix now" not in response.text
    assert "Evidence summary" in response.text
    assert "Audit archive summary" in response.text
    assert "Phoenix provides trace/eval evidence" in response.text
    assert "AgentGate adds AgentPack-defined policy thresholds" in response.text
    assert "Effective policy" in response.text
    assert "blocks release" in response.text
    assert "Release controls detail" in response.text
    assert "Audit scope, coverage, and reproducibility" in response.text
    assert "Reproducibility recipe" in response.text
    assert "decision-brief" in response.text
    assert (
        response.text.index("Why blocked")
        < response.text.index("Release controls generated from this blocked failure")
        < response.text.index('id="future-verification"')
        < response.text.index("Evidence summary")
    )
    assert response.text.index('id="release-controls"') < response.text.index(
        'id="future-verification"'
    )
    assert "These are not debug notes" in response.text
    assert "future release requirements" in response.text
    assert response.text.count("is BLOCKED before production") == 1
    assert "Non-authoritative explanation" not in response.text
    assert "Gemini semantic diagnosis (non-authoritative" in response.text
    assert "Explanatory only. Gemini is not used for BLOCKED/APPROVED." in response.text
    assert "AG-RG-001" in response.text
    assert "Generated release controls" in response.text
    assert (
        "regression_gates.json is the technical artifact backing generated release controls."
        in response.text
    )
    assert "Developer remediation context" in response.text
    assert "Copy remediation context" in response.text
    assert "Copy debug prompt" not in response.text
    assert (
        "Hard block deep_investigate_alert unless user_role is developer or sre." in response.text
    )
    release_controls_chunk = response.text[
        response.text.index('id="release-controls"') : response.text.index('id="evidence-summary"')
    ]
    evidence_summary_chunk = response.text[
        response.text.index('id="evidence-summary"') : response.text.index('id="audit-archive"')
    ]
    assert "Copy remediation context" not in release_controls_chunk
    assert "Copy remediation context" not in evidence_summary_chunk
    assert ">View</button>" in evidence_summary_chunk
    assert 'title="View evidence"' in evidence_summary_chunk
    assert 'data-copy="' not in evidence_summary_chunk
    assert 'class="decision-evidence-table"' in response.text
    assert 'class="blocker-findings-table"' in response.text
    assert "Show all" not in response.text
    assert "blocker-pager-btn" in response.text
    if 'class="gate-binding-table"' in response.text:
        assert 'data-label="Suite metric"' in response.text
    assert "report-sticky-nav" in response.text
    assert "regression_" in response.text or "StrictPolicyEnforcement" in response.text
    assert "Rerun release check after fixes land." in response.text
    assert response.text.count("Non-developer must not run deep investigation") >= 1
    assert response.text.count("Ambiguous incident question must not escalate") >= 1


def test_latest_report_shows_v21_approved_not_perfect_story(
    tmp_path: Path, monkeypatch: Any
) -> None:
    latest_dir = tmp_path / "latest"
    _write_artifacts("v2.1", latest_dir, tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/reports/latest")

    assert response.status_code == 200
    assert "APPROVED" in response.text
    assert "Approved, not perfect." in response.text
    assert "All inherited blocker controls passed." in response.text
    assert "Non-blocking warnings remain visible for review." in response.text
    assert "Failed, non-blocking controls" in response.text
    assert response.text.count("<h2>Evidence summary</h2>") == 1
    assert response.text.count("<h2>Audit archive summary</h2>") == 1
    assert response.text.count('aria-label="Audit artifacts"') == 1
    assert "Copy debug prompt" not in response.text
    primary_flow = response.text.split('aria-label="Audit appendices"', 1)[0]
    assert "Copy remediation context" not in primary_flow
    assert "Failed controls</span>" not in response.text
    assert "Warning controls</span>" in response.text
    assert response.text.index("Future Verification") < response.text.index(
        "Release controls status"
    )
    assert "Decision impact if failed" in response.text
    assert "Blocking requirement" in response.text
    assert 'impact-badge impact-blocker">blocker</span>' not in response.text
    assert "Technical tool success rate" in response.text
    assert "Incident analysis format compliance" in response.text
    assert "No new release controls were generated for this evidence window." in response.text


def test_latest_report_missing_state(tmp_path: Path, monkeypatch: Any) -> None:
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(tmp_path / "missing"))
    client = TestClient(app)

    response = client.get("/reports/latest")

    assert response.status_code == 404
    assert "No candidate report yet" in response.text


def test_latest_run_api_returns_dashboard_payload(tmp_path: Path, monkeypatch: Any) -> None:
    latest_dir = tmp_path / "latest"
    _write_artifacts("v2.1", latest_dir, tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/api/agentgate/runs/latest")

    assert response.status_code == 200
    payload = response.json()
    assert payload["status"] == "ready"
    assert payload["decision"] == "APPROVED"
    assert payload["report_url"] == "/reports/latest"
    assert len(payload["artifact_links"]) == 9
    artifact_filenames = {link["filename"] for link in payload["artifact_links"]}
    assert "control_verification_results.json" in artifact_filenames
    assert payload["future_verification"]["status"] in {
        "verified",
        "not_available",
        "not_applicable",
        "failed",
    }


def test_artifact_route_serves_allowlisted_json_only(tmp_path: Path, monkeypatch: Any) -> None:
    latest_dir = tmp_path / "latest"
    _write_artifacts("v2", latest_dir, tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    allowed = client.get("/artifacts/release_decision.json")
    blocked = client.get("/artifacts/../pyproject.toml")
    unknown = client.get("/artifacts/not_real.json")

    assert allowed.status_code == 200
    assert allowed.json()["decision"] == "BLOCKED"
    control_verification = client.get("/artifacts/control_verification_results.json")
    assert control_verification.status_code == 200
    assert control_verification.json()["artifact_type"] == "control_verification_results"
    assert blocked.status_code == 404
    assert unknown.status_code == 404


def test_release_check_api_passes_release_controls_ref(tmp_path: Path, monkeypatch: Any) -> None:
    latest_dir = tmp_path / "latest"
    evidence = _seed("v2.1", tmp_path)
    controls = tmp_path / "regression_gates.json"
    shutil.copy(
        Path(__file__).resolve().parents[2]
        / "examples"
        / "artifacts"
        / "reference-v2"
        / "regression_gates.json",
        controls,
    )
    calls: list[dict[str, Any]] = []
    real_run_release_check = release_check_module.run_release_check

    def fake_run_release_check(**kwargs: Any) -> dict[str, Any]:
        calls.append(kwargs)
        return real_run_release_check(
            evidence_path=kwargs["evidence_path"],
            output_dir=kwargs["output_dir"],
            diagnosis_mode=kwargs["diagnosis_mode"],
            release_config=kwargs["release_config"],
        )

    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    monkeypatch.setattr(
        routes_dashboard.release_check_module,
        "run_release_check",
        fake_run_release_check,
    )
    client = TestClient(app)

    response = client.post(
        "/api/agentgate/release-check",
        json={
            "source": "local",
            "evidence": str(evidence),
            "agent_version": "v2.1",
            "release_controls_ref": str(controls),
        },
    )

    assert response.status_code == 200
    payload = response.json()
    assert payload["future_verification"]["status"] == "verified"
    assert payload["future_verification"]["total_controls"] == 4
    assert payload["future_verification"]["passed"] == 4
    assert payload["future_verification"]["blocking_failed"] == 0
    assert calls[0]["release_config"].release_controls_ref == controls
    assert calls[0]["release_config"].release_controls_resolution_source == "api_request"


def test_release_check_api_defaults_to_phoenix_gemini(tmp_path: Path, monkeypatch: Any) -> None:
    latest_dir = tmp_path / "latest"
    calls: list[dict[str, Any]] = []

    def fake_run_release_check_from_phoenix_mcp(**kwargs: Any) -> dict[str, Any]:
        calls.append(kwargs)
        _write_artifacts("v2", kwargs["output_dir"], tmp_path)
        return {
            "agent_id": "stability_ops_ai",
            "agent_version": "v2",
            "decision": "BLOCKED",
            "critical_findings": 1,
            "reviewed_safe": 0,
            "artifact_paths": {},
            "diagnosis_metadata": {},
        }

    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    monkeypatch.setenv("PHOENIX_PROJECT_NAME", "agentgate-reference-ops-demo")
    monkeypatch.setattr(
        routes_dashboard.release_check_module,
        "run_release_check_from_phoenix_mcp",
        fake_run_release_check_from_phoenix_mcp,
    )
    client = TestClient(app)

    response = client.post("/api/agentgate/release-check", json={})

    assert response.status_code == 200
    payload = response.json()
    assert payload["status"] == "complete"
    assert payload["source"] == "phoenix"
    assert payload["fallback_used"] is False
    assert "events" not in payload
    assert payload["journey"]["label"] == "No-ship"
    assert payload["journey"]["report_url"] == "/reports/latest"
    assert payload["journey"]["headline"] == "No-ship decision written for v2."
    assert "generated release controls" in payload["journey"]["summary"]
    assert calls == [
        {
            "output_dir": latest_dir,
            "project_identifier": "agentgate-reference-ops-demo",
            "agent_version": "v2",
            "last_n_minutes": 1440,
            "diagnosis_mode": "gemini",
            "release_config": ReleaseCheckConfig(),
        }
    ]


def test_release_check_api_returns_ship_with_warnings_journey_for_v21_candidate(
    tmp_path: Path, monkeypatch: Any
) -> None:
    latest_dir = tmp_path / "latest"

    def fake_run_release_check_from_phoenix_mcp(**kwargs: Any) -> dict[str, Any]:
        _write_artifacts("v2.1", kwargs["output_dir"], tmp_path)
        return {
            "agent_id": "stability_ops_ai",
            "agent_version": "v2.1",
            "decision": "APPROVED",
            "critical_findings": 0,
            "reviewed_safe": 2,
            "artifact_paths": {},
            "diagnosis_metadata": {},
        }

    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    monkeypatch.setenv("PHOENIX_PROJECT_NAME", "agentgate-reference-ops-demo")
    monkeypatch.setattr(
        routes_dashboard.release_check_module,
        "run_release_check_from_phoenix_mcp",
        fake_run_release_check_from_phoenix_mcp,
    )
    client = TestClient(app)

    response = client.post("/api/agentgate/release-check", json={"agent_version": "v2.1"})

    assert response.status_code == 200
    payload = response.json()
    assert payload["journey"]["label"] == "Ship with warnings"
    assert payload["journey"]["headline"] == "Ship decision written for v2.1."
    assert "APPROVED with" in payload["journey"]["summary"]
    assert "non-blocking control warning" in payload["journey"]["summary"]
    assert payload["journey"]["report_url"] == "/reports/latest"


def test_run_result_copy_calls_out_non_blocking_warning_variance() -> None:
    journey = routes_dashboard._run_result_copy(
        {
            "agent_version": "v2.1",
            "decision": "APPROVED",
            "report_url": "/reports/latest",
            "metrics": [
                {
                    "passes_threshold": False,
                    "decision_impact": "warning",
                }
            ],
        }
    )

    assert journey["label"] == "Ship with warnings"
    assert journey["headline"] == "Ship decision written for v2.1."
    assert "APPROVED with 1 non-blocking control warning" in journey["summary"]


def test_release_check_api_returns_clear_error_without_fallback(
    monkeypatch: Any, tmp_path: Path
) -> None:
    def fake_run_release_check_from_phoenix_mcp(**kwargs: Any) -> dict[str, Any]:
        raise ValueError("Phoenix MCP returned no AgentGate evidence records.")

    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(tmp_path / "latest"))
    monkeypatch.setattr(
        routes_dashboard.release_check_module,
        "run_release_check_from_phoenix_mcp",
        fake_run_release_check_from_phoenix_mcp,
    )
    client = TestClient(app)

    response = client.post("/api/agentgate/release-check", json={})

    assert response.status_code == 503
    payload = response.json()
    assert payload["status"] == "error"
    assert payload["default_source"] == "phoenix"
    assert payload["fallback_used"] is False
    assert "Phoenix MCP returned no AgentGate evidence records" in payload["message"]


def test_report_context_includes_gate_binding_and_fingerprints(tmp_path: Path) -> None:
    latest_dir = tmp_path / "latest"
    _write_artifacts("v2", latest_dir, tmp_path)

    context = build_report_context(latest_dir)

    assert context["gate_binding_rows"]
    assert context["artifact_fingerprints"]
    assert context["decision_brief"]
    assert context["blocking_drivers"]
    assert context["verdict_panel"]["headline"]
    assert context["why_blocked"]["blocking_drivers"]
    assert context["fix_now"]["tasks"]
    assert context["audit_archive_summary"]["fields"]
    assert context["appendix_sections"]["controls"]
    assert context["executive_verdict"]["actions"]
    assert context["normalized_regression_gates"]
    assert context["audit_summary"]["regression_gate_count"] >= 1
    if context["critical_findings"]:
        assert "expected_intent_id" in context["critical_findings"][0]


def _inject_nonblocking_inherited_control_failure(output_dir: Path) -> None:
    def update_verification(payload: dict[str, Any]) -> None:
        payload["results"].append(
            {
                "gate_id": "technical_tool_success_rate_within_threshold",
                "control_title": "Technical tool success rate must stay within threshold.",
                "verification_status": "FAIL",
                "blocking": False,
                "matched_metric_ids": ["technical_tool_success_rate"],
                "candidate_values": {"technical_tool_success_rate": 0.5},
            }
        )
        summary = payload.setdefault("summary", {})
        summary["failed"] = int(summary.get("failed", 0)) + 1
        summary["passed"] = max(0, int(summary.get("passed", 0)) - 1)

    _rewrite_json(output_dir / "control_verification_results.json", update_verification)

    def update_decision(payload: dict[str, Any]) -> None:
        future = payload.setdefault("future_verification", {})
        future["failed"] = int(future.get("failed", 0)) + 1

    _rewrite_json(output_dir / "release_decision.json", update_decision)


def test_report_renders_future_verification_not_applicable_for_v2(
    tmp_path: Path, monkeypatch: Any
) -> None:
    latest_dir = tmp_path / "latest"
    _write_artifacts("v2", latest_dir, tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/reports/latest")

    assert response.status_code == 200
    assert "Future Verification" in response.text
    assert "Not applicable" in response.text
    assert "Future Verification is not applicable" in response.text
    assert "follow-up candidate must verify" in response.text


def test_report_renders_future_verification_verified_with_control_rows(
    tmp_path: Path, monkeypatch: Any
) -> None:
    latest_dir = tmp_path / "latest"
    controls = (
        Path(__file__).resolve().parents[2]
        / "examples"
        / "artifacts"
        / "reference-v2"
        / "regression_gates.json"
    )
    run_release_check(
        _seed("v2.1", tmp_path),
        latest_dir,
        release_config=ReleaseCheckConfig(release_controls_ref=controls),
    )
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/reports/latest")

    assert response.status_code == 200
    assert "Future Verification" in response.text
    assert "Verified" in response.text
    assert "verified the release controls generated by the blocked" in response.text
    assert "All inherited blocker controls passed." in response.text
    assert "Decision impact if failed" in response.text
    assert "control_verification_results.json" in response.text
    assert "All controls passed" not in response.text


def test_report_verified_with_nonblocking_failures_uses_correct_copy(
    tmp_path: Path, monkeypatch: Any
) -> None:
    latest_dir = tmp_path / "latest"
    controls = (
        Path(__file__).resolve().parents[2]
        / "examples"
        / "artifacts"
        / "reference-v2"
        / "regression_gates.json"
    )
    run_release_check(
        _seed("v2.1", tmp_path),
        latest_dir,
        release_config=ReleaseCheckConfig(release_controls_ref=controls),
    )
    _inject_nonblocking_inherited_control_failure(latest_dir)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/reports/latest")

    assert response.status_code == 200
    assert "All inherited blocker controls passed" in response.text
    assert "Non-blocking warnings remain visible for review." in response.text
    assert "All controls passed" not in response.text
    assert "non-blocking" in response.text


def test_report_renders_future_verification_not_available(tmp_path: Path, monkeypatch: Any) -> None:
    latest_dir = tmp_path / "latest"
    monkeypatch.setattr(
        "backend.agentgate.release.regression_gate_verifier.BUNDLED_REFERENCE_REGRESSION_GATES",
        tmp_path / "missing" / "regression_gates.json",
    )
    _write_artifacts("v2.1", latest_dir, tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/reports/latest")

    assert response.status_code == 200
    assert "Not available" in response.text
    assert "No previous regression_gates.json was found" in response.text
    assert "gate-bound blocker metrics only" in response.text


def test_landing_v2_card_shows_future_verification_not_applicable(
    tmp_path: Path, monkeypatch: Any
) -> None:
    latest_dir = tmp_path / "latest"
    v2_dir = tmp_path / "v2"
    v21_dir = tmp_path / "v21"
    _write_artifacts("v2.1", latest_dir, tmp_path)
    _write_artifacts("v2", v2_dir, tmp_path)
    _write_artifacts("v2.1", v21_dir, tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/")

    assert response.status_code == 200
    assert "AgentGate blocked v2 before release and generated controls" in response.text


def test_landing_v21_card_shows_future_verification_verified(
    tmp_path: Path, monkeypatch: Any
) -> None:
    latest_dir = tmp_path / "latest"
    v2_dir = tmp_path / "v2"
    v21_dir = tmp_path / "v21"
    _write_artifacts("v2.1", latest_dir, tmp_path)
    _write_artifacts("v2", v2_dir, tmp_path)
    _write_artifacts("v2.1", v21_dir, tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/")

    assert response.status_code == 200
    assert "v2.1 verified the controls generated by the blocked v2 release." in response.text
    assert "All inherited blocker controls passed." in response.text


def test_landing_v21_missing_controls_shows_not_available_copy(
    tmp_path: Path, monkeypatch: Any
) -> None:
    latest_dir = tmp_path / "latest"
    v2_dir = tmp_path / "v2"
    v21_dir = tmp_path / "v21"
    monkeypatch.setattr(
        "backend.agentgate.release.regression_gate_verifier.BUNDLED_REFERENCE_REGRESSION_GATES",
        tmp_path / "missing" / "regression_gates.json",
    )
    _write_artifacts("v2.1", latest_dir, tmp_path)
    _write_artifacts("v2", v2_dir, tmp_path)
    _write_artifacts("v2.1", v21_dir, tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/")

    assert response.status_code == 200
    assert "v2.1 is APPROVED from current gate-bound blocker metrics only." in response.text


def test_run_page_includes_future_verification_note_and_card(
    tmp_path: Path, monkeypatch: Any
) -> None:
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(tmp_path / "missing"))
    client = TestClient(app)

    response = client.get("/run")

    assert response.status_code == 200
    assert "v2.1 verifies the release controls generated by the blocked v2 run." in response.text
    assert 'id="run-future-verification-card"' in response.text
    assert "showFutureVerificationCard" in response.text


def test_future_verification_run_card_copy_variants() -> None:
    assert future_verification_run_card_copy({"status": "not_applicable"}) == {
        "summary": "No previous release controls were expected for this candidate.",
    }
    assert future_verification_run_card_copy({"status": "not_available"}) == {
        "summary": (
            "Future verification not available. Decision is based on current blocker metrics only."
        ),
    }
    assert future_verification_run_card_copy(
        {"status": "verified", "blocking_failed": 0, "failed": 1}
    ) == {
        "summary": ("Inherited blocker controls passed. Non-blocking controls remain visible."),
    }
    assert future_verification_run_card_copy(
        {"status": "verified", "blocking_failed": 0, "failed": 0}
    ) == {
        "summary": "Inherited blocker controls passed.",
    }


def test_blocked_report_remediation_hierarchy(tmp_path: Path, monkeypatch: Any) -> None:
    latest_dir = tmp_path / "latest"
    _write_artifacts("v2", latest_dir, tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/reports/latest")
    text = response.text

    assert "Developer remediation context" in text
    assert "Copy remediation context" in text
    assert "Copy debug prompt" not in text
    assert 'remediation-disclosure"' in text
    assert '<details class="evidence-disclosure remediation-disclosure" open' not in text
    assert "contexts available. This does not affect the release decision." in text
    assert 'id="release-controls"' in text
    release_controls_chunk = text[
        text.index('id="release-controls"') : text.index('id="evidence-summary"')
    ]
    evidence_summary_chunk = text[
        text.index('id="evidence-summary"') : text.index('id="audit-archive"')
    ]
    assert "Copy remediation context" not in release_controls_chunk
    assert "Copy remediation context" not in evidence_summary_chunk
    assert ">View</button>" in evidence_summary_chunk
    assert 'title="View evidence"' in evidence_summary_chunk
    assert 'data-copy="' not in evidence_summary_chunk
    assert text.index('id="audit-artifacts"') < text.index(
        'class="evidence-disclosure remediation-disclosure"'
    )
    assert "remediation-appendix-band" in text

    remediation_chunk = text.split('class="evidence-disclosure remediation-disclosure"', 1)[
        1
    ].split("</details>", 1)[0]
    assert remediation_chunk.count('<article class="remediation-entry">') <= 4
    assert "<dt>Summary</dt>" not in remediation_chunk
    assert 'class="button copy-button copy-button-secondary"' in remediation_chunk
    if (context := build_report_context(latest_dir).get("developer_remediation")) and context.get(
        "truncated"
    ):
        assert "Showing top 4 remediation contexts" in text
    visible_remediation = re.sub(r'data-copy="[^"]*"', "", remediation_chunk, flags=re.DOTALL)
    assert "Investigate why candidate" not in visible_remediation
    assert "# AgentGate Candidate Debug" not in visible_remediation
    assert "## Please inspect" not in visible_remediation


def test_approved_report_primary_flow_has_no_remediation_copy(
    tmp_path: Path, monkeypatch: Any
) -> None:
    latest_dir = tmp_path / "latest"
    _write_artifacts("v2.1", latest_dir, tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/reports/latest")
    text = response.text

    assert "Future Verification" in text
    assert "All inherited blocker controls passed." in text
    assert "Approved, not perfect." in text
    assert "Copy debug prompt" not in text
    primary_flow = text.split('aria-label="Audit appendices"', 1)[0]
    assert "Copy remediation context" not in primary_flow


def test_report_context_marks_local_jsonl_as_fallback(tmp_path: Path) -> None:
    latest_dir = tmp_path / "latest"
    _write_artifacts("v2", latest_dir, tmp_path)
    decision_path = latest_dir / "release_decision.json"
    decision = json.loads(decision_path.read_text(encoding="utf-8"))
    decision["evidence_source"]["type"] = "local_jsonl"
    decision_path.write_text(
        json.dumps(decision, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    context = build_report_context(latest_dir)

    assert context["source_is_local"] is True
    assert context["release_decision"]["agent_version"] == "v2"
