"""Website and report copy must match the truthful reference demo narrative."""

from __future__ import annotations

from pathlib import Path

from backend.agentgate.main import app
from fastapi.testclient import TestClient

REPO_ROOT = Path(__file__).resolve().parents[2]
EXAMPLES_BLOCKED = REPO_ROOT / "examples" / "artifacts" / "reference-v2"
EXAMPLES_APPROVED = REPO_ROOT / "examples" / "artifacts" / "reference-v21"

FORBIDDEN_WEBSITE_PATTERNS = (
    "two AI agents",
    "Release Authority Agent",
    "Release Controls Agent",
    "Every Failed Trace",
    "every failed trace",
    "all controls passed",
    "Copy debug prompt",
)

FORBIDDEN_TARGET_AGENT_MCP = (
    "uses MCP to access enterprise tools",
    "target agent uses MCP",
)


def _write_reference_artifacts(tmp_path: Path) -> tuple[Path, Path, Path]:
    from backend.agentgate.demo.trace_seed_generator import write_seed_evidence
    from backend.agentgate.release.release_check import run_release_check

    v2_dir = tmp_path / "v2"
    v21_dir = tmp_path / "v21"
    latest_dir = tmp_path / "latest"
    write_seed_evidence("v2", tmp_path / "seed_v2.jsonl")
    write_seed_evidence("v2.1", tmp_path / "seed_v21.jsonl")
    run_release_check(tmp_path / "seed_v2.jsonl", v2_dir)
    run_release_check(
        tmp_path / "seed_v21.jsonl",
        v21_dir,
        release_config=__import__(
            "backend.agentgate.core.product_config", fromlist=["ReleaseCheckConfig"]
        ).ReleaseCheckConfig(release_controls_ref=v2_dir / "regression_gates.json"),
    )
    run_release_check(tmp_path / "seed_v21.jsonl", latest_dir)
    return v2_dir, v21_dir, latest_dir


def test_homepage_demo_wording(tmp_path, monkeypatch) -> None:
    v2_dir, _, latest_dir = _write_reference_artifacts(tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/")

    assert response.status_code == 200
    text = response.text
    assert "Phoenix evidence path" in text
    assert "Policy expected DENY" in text
    assert "blocked v2 release" in text
    assert "Candidate evidence" in text
    for phrase in FORBIDDEN_WEBSITE_PATTERNS:
        assert phrase not in text


def test_run_page_demo_wording(tmp_path, monkeypatch) -> None:
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(tmp_path / "missing"))
    client = TestClient(app)

    response = client.get("/run")

    assert response.status_code == 200
    text = response.text
    assert "candidate evidence" in text
    assert "v2.1 verifies the release controls generated by the blocked v2 run." in text
    for phrase in FORBIDDEN_TARGET_AGENT_MCP:
        assert phrase not in text


def test_v2_report_section_order_and_copy(tmp_path, monkeypatch) -> None:
    v2_dir, _, _ = _write_reference_artifacts(tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(v2_dir))
    client = TestClient(app)

    response = client.get("/reports/latest")
    text = response.text

    assert response.status_code == 200
    assert text.index('id="release-controls"') < text.index('id="future-verification"')
    assert "These are not debug notes" in text
    assert "future release requirements" in text
    assert "Future Verification is not applicable" in text
    for phrase in FORBIDDEN_WEBSITE_PATTERNS:
        assert phrase not in text


def test_v21_report_approved_wording(tmp_path, monkeypatch) -> None:
    _, v21_dir, _ = _write_reference_artifacts(tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(v21_dir))
    client = TestClient(app)

    response = client.get("/reports/latest")
    text = response.text

    assert response.status_code == 200
    assert "verified the release controls generated by the blocked v2 run" in text
    assert "All inherited blocker controls passed" in text
    assert "Non-blocking warnings remain visible" in text
    assert "All controls passed" not in text
    assert "Why blocked" not in text
    assert "Failed controls</span>" not in text
    for phrase in FORBIDDEN_WEBSITE_PATTERNS:
        assert phrase not in text


def test_bundled_reference_html_has_no_forbidden_phrases() -> None:
    for bundle in (EXAMPLES_BLOCKED, EXAMPLES_APPROVED):
        html = (bundle / "release_report.html").read_text(encoding="utf-8")
        for phrase in FORBIDDEN_WEBSITE_PATTERNS:
            assert phrase not in html


def test_landing_intervention_card_order(tmp_path, monkeypatch) -> None:
    v2_dir, v21_dir, latest_dir = _write_reference_artifacts(tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    response = client.get("/")
    text = response.text

    assert (
        text.index("Policy expected DENY")
        < text.index("deep_investigate_alert")
        < text.index("blocked v2 release")
    )


def test_approved_report_primary_flow_before_appendix(tmp_path, monkeypatch) -> None:
    _, v21_dir, _ = _write_reference_artifacts(tmp_path)
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(v21_dir))
    client = TestClient(app)

    response = client.get("/reports/latest")
    primary = response.text.split('aria-label="Audit appendices"', 1)[0]

    assert (
        primary.index("Future Verification")
        < primary.index("Release controls status")
        < primary.index("Evidence summary")
    )
