"""End-to-end truth checks for bundled reference release intervention demo artifacts."""

from __future__ import annotations

import json
import re
from pathlib import Path

from backend.agentgate.main import app
from backend.agentgate.web.report_renderer import (
    CORE_ARTIFACT_FILENAMES,
    HTML_ARTIFACT_FILENAME,
    build_report_context,
    latest_artifacts_exist,
)
from fastapi.testclient import TestClient

REPO_ROOT = Path(__file__).resolve().parents[2]
EXAMPLES_ROOT = REPO_ROOT / "examples" / "artifacts"
REFERENCE_BLOCKED = EXAMPLES_ROOT / "reference-v2"
REFERENCE_APPROVED = EXAMPLES_ROOT / "reference-v21"

REQUIRED_AUDIT_ARTIFACTS = CORE_ARTIFACT_FILENAMES | {
    HTML_ARTIFACT_FILENAME,
    "dangerous_sessions.json",
}


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _failed_metrics(output_dir: Path, *, impact: str) -> list[str]:
    metrics = _load_json(output_dir / "metrics_summary.json")["metrics"]
    return [
        metric["name"]
        for metric in metrics
        if metric.get("decision_impact") == impact and not metric.get("passes_threshold")
    ]


def test_reference_bundles_include_core_audit_contract() -> None:
    for bundle in (REFERENCE_BLOCKED, REFERENCE_APPROVED):
        assert bundle.is_dir()
        for filename in REQUIRED_AUDIT_ARTIFACTS:
            assert (bundle / filename).exists(), f"missing {filename} in {bundle.name}"
        assert latest_artifacts_exist(bundle)


def test_reference_v2_blocked_with_generated_release_controls() -> None:
    decision = _load_json(REFERENCE_BLOCKED / "release_decision.json")
    gates = _load_json(REFERENCE_BLOCKED / "regression_gates.json")

    assert decision["agent_version"] == "v2"
    assert decision["decision"] == "BLOCKED"
    assert _failed_metrics(REFERENCE_BLOCKED, impact="blocker")
    assert gates["regression_gates"]
    assert all(gate.get("gate_id") for gate in gates["regression_gates"])

    context = build_report_context(REFERENCE_BLOCKED)
    assert context["release_decision"]["decision"] == "BLOCKED"
    assert context["normalized_regression_gates"]
    assert context["why_blocked"]["blocking_drivers"]

    html = (REFERENCE_BLOCKED / "release_report.html").read_text(encoding="utf-8")
    assert "BLOCKED" in html
    assert "Why blocked" in html
    assert "Release controls generated" in html
    assert "Developer remediation context" in html
    assert "Copy remediation context" in html
    assert "Copy debug prompt" not in html
    assert '<details class="evidence-disclosure remediation-disclosure" open' not in html
    assert html.count('<article class="remediation-entry">') <= 4
    assert html.index('id="audit-artifacts"') < html.index(
        'class="evidence-disclosure remediation-disclosure"'
    )
    if build_report_context(REFERENCE_BLOCKED)["developer_remediation"]["truncated"]:
        assert "Showing top 4 remediation contexts" in html
    remediation_chunk = html.split('class="evidence-disclosure remediation-disclosure"', 1)[
        1
    ].split("</details>", 1)[0]
    assert "<dt>Summary</dt>" not in remediation_chunk
    assert 'class="button copy-button copy-button-secondary"' in remediation_chunk
    visible_remediation = re.sub(r'data-copy="[^"]*"', "", remediation_chunk, flags=re.DOTALL)
    assert "Investigate why candidate" not in visible_remediation
    assert "# AgentGate Candidate Debug" not in visible_remediation


def test_reference_v21_approved_with_warning_only_variance() -> None:
    decision = _load_json(REFERENCE_APPROVED / "release_decision.json")
    gates = _load_json(REFERENCE_APPROVED / "regression_gates.json")

    assert decision["agent_version"] == "v2.1"
    assert decision["decision"] == "APPROVED"
    assert not _failed_metrics(REFERENCE_APPROVED, impact="blocker")
    assert _failed_metrics(REFERENCE_APPROVED, impact="warning")
    assert gates["regression_gates"] == []

    context = build_report_context(REFERENCE_APPROVED)
    assert context["release_decision"]["decision"] == "APPROVED"
    assert context["verdict_panel"]["headline"]
    assert any(
        not metric.get("passes_threshold") and metric.get("decision_impact") == "warning"
        for metric in context["metrics"]
    )

    html = (REFERENCE_APPROVED / "release_report.html").read_text(encoding="utf-8")
    assert "APPROVED" in html
    assert "Approved, not perfect" in html
    assert "Why blocked" not in html
    assert "Future Verification" in html
    assert "verified the release controls generated by the blocked v2 run" in html
    assert "All inherited blocker controls passed" in html
    assert "Copy debug prompt" not in html
    assert html.count("<h2>Evidence preview</h2>") == 1
    assert html.count("<h2>Audit status</h2>") == 1
    assert html.count('aria-label="Audit artifacts"') == 1
    primary_flow = html.split('aria-label="Audit appendices"', 1)[0]
    assert "Copy remediation context" not in primary_flow


def test_landing_uses_bundled_reference_intervention_proof(monkeypatch) -> None:
    latest_dir = REFERENCE_APPROVED
    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(latest_dir))
    client = TestClient(app)

    landing = client.get("/")
    run_page = client.get("/run")

    assert landing.status_code == 200
    assert "Featured release intervention" in landing.text
    assert "BLOCKED" in landing.text
    assert "Generated release controls" in landing.text
    assert "verified the controls generated by the blocked v2 release." in landing.text
    assert "Approved, not perfect" in landing.text
    assert "v2.1" in landing.text

    assert run_page.status_code == 200
    assert "Generate future controls if blocked" in run_page.text
    assert "Run release check" in run_page.text
    assert "Last completed run:" in run_page.text
    assert "Ship (APPROVED)" in run_page.text


def test_latest_report_reflects_reference_blocked_and_approved_bundles(
    monkeypatch,
) -> None:
    client = TestClient(app)

    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(REFERENCE_BLOCKED))
    blocked_report = client.get("/reports/latest")
    assert blocked_report.status_code == 200
    assert "Why blocked" in blocked_report.text
    assert "Release controls generated" in blocked_report.text
    assert "Technical backing: regression_gates.json" in blocked_report.text

    monkeypatch.setenv("AGENTGATE_LATEST_ARTIFACT_DIR", str(REFERENCE_APPROVED))
    approved_report = client.get("/reports/latest")
    assert approved_report.status_code == 200
    assert "Approved, not perfect" in approved_report.text
    assert "Why blocked" not in approved_report.text
    assert "Future Verification" in approved_report.text
    assert "verified the release controls generated by the blocked v2 run" in approved_report.text
    assert "Failed, non-blocking controls" in approved_report.text
